"""
GitHub deployment tool — pushes project files to a GitHub repository.

Uses the GitHub REST API with a Classic Personal Access Token (PAT).
Required scope: repo (for creating and pushing to repos).

Flow:
  1. Check if repo exists → create it if not
  2. Get default branch SHA (or create initial commit)
  3. Create a tree with all project files
  4. Create a commit pointing to the new tree
  5. Update the branch reference
  6. Stream SSE progress back to the client
"""
from __future__ import annotations

import base64
import json
from pathlib import Path
from typing import AsyncGenerator

_API = "https://api.github.com"

SKIP_PATHS = frozenset(
    [".git", "node_modules", ".expo", "__pycache__", ".pip_packages",
     ".tsbuildinfo", "dist", "build", ".next"]
)


def _headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
    }


def _collect_files(project_path: Path) -> dict[str, bytes]:
    """Collect all deployable files as raw bytes."""
    files: dict[str, bytes] = {}
    for f in sorted(project_path.rglob("*")):
        if not f.is_file():
            continue
        if any(p in f.parts for p in SKIP_PATHS):
            continue
        rel = str(f.relative_to(project_path))
        # Skip files > 5MB
        if f.stat().st_size > 5 * 1024 * 1024:
            continue
        try:
            files[rel] = f.read_bytes()
        except Exception:
            pass
    return files


async def push_to_github(
    project_id: str,
    project_path: Path,
    token: str,
    repo_name: str,
    private: bool = False,
    commit_message: str = "Initial commit from Veylor",
    branch: str = "main",
) -> AsyncGenerator[str, None]:
    """
    Push project files to GitHub (creates repo if it doesn't exist).
    Yields SSE-formatted strings for real-time streaming.

    SSE event shapes:
      {"type": "start",    "message": "..."}
      {"type": "log",      "message": "...", "level": "info"|"error"|"warning"}
      {"type": "url",      "url": "https://github.com/...", "repo": "..."}
      {"type": "error",    "message": "..."}
      {"type": "done",     "url": "https://github.com/...", "repo": "..."}
    """
    import aiohttp

    KEEPALIVE = ": ping\n\n"

    def evt(data: dict) -> str:
        return f"data: {json.dumps(data, ensure_ascii=False)}\n\n"

    if not token or not token.strip():
        yield evt({"type": "error", "message": "GitHub token is required."})
        return

    token = token.strip()
    hdrs = _headers(token)

    async with aiohttp.ClientSession() as session:
        # ── Step 1: Get authenticated user ────────────────────────────────────
        yield evt({"type": "start", "message": "🔑 التحقق من GitHub token..."})
        yield KEEPALIVE

        async with session.get(f"{_API}/user", headers=hdrs) as resp:
            if resp.status != 200:
                body = await resp.text()
                yield evt({"type": "error", "message": f"GitHub authentication failed ({resp.status}): {body[:200]}"})
                return
            user_data = await resp.json()
            username = user_data.get("login", "")

        yield evt({"type": "log", "message": f"✅ مرحباً {username}!", "level": "info"})

        full_repo = f"{username}/{repo_name}"
        repo_url = f"https://github.com/{full_repo}"

        # ── Step 2: Create repo if it doesn't exist ───────────────────────────
        yield evt({"type": "log", "message": f"📦 التحقق من الـ repo: {full_repo}...", "level": "info"})
        yield KEEPALIVE

        async with session.get(f"{_API}/repos/{full_repo}", headers=hdrs) as resp:
            repo_exists = resp.status == 200

        if not repo_exists:
            yield evt({"type": "log", "message": f"🆕 إنشاء repo جديد: {repo_name}...", "level": "info"})
            create_payload = {
                "name": repo_name,
                "private": private,
                "auto_init": False,
                "description": f"Generated by Veylor AI Agent — project {project_id}",
            }
            async with session.post(f"{_API}/user/repos", headers=hdrs, json=create_payload) as resp:
                if resp.status not in (200, 201):
                    body = await resp.text()
                    yield evt({"type": "error", "message": f"Failed to create repo ({resp.status}): {body[:300]}"})
                    return
            yield evt({"type": "log", "message": f"✅ تم إنشاء الـ repo: {repo_url}", "level": "info"})
        else:
            yield evt({"type": "log", "message": f"✅ الـ repo موجود: {repo_url}", "level": "info"})

        yield evt({"type": "url", "url": repo_url, "repo": full_repo})

        # ── Step 3: Collect project files ─────────────────────────────────────
        yield evt({"type": "log", "message": "📂 جمع ملفات المشروع...", "level": "info"})
        yield KEEPALIVE

        files = _collect_files(project_path)
        if not files:
            yield evt({"type": "error", "message": "No files found in project directory"})
            return

        yield evt({"type": "log", "message": f"📄 {len(files)} ملف جاهز للرفع", "level": "info"})

        # ── Step 4: Get current branch SHA (if branch exists) ─────────────────
        parent_sha: str | None = None

        async with session.get(
            f"{_API}/repos/{full_repo}/git/ref/heads/{branch}", headers=hdrs
        ) as resp:
            if resp.status == 200:
                ref_data = await resp.json()
                parent_sha = ref_data["object"]["sha"]
                yield evt({"type": "log", "message": f"🔀 Branch موجود: {branch} @ {parent_sha[:7]}", "level": "info"})
            else:
                yield evt({"type": "log", "message": f"🆕 Branch جديد: {branch}", "level": "info"})

        # ── Step 5: Create blobs for each file ────────────────────────────────
        yield evt({"type": "log", "message": "⬆️ رفع الملفات إلى GitHub...", "level": "info"})
        yield KEEPALIVE

        tree_items = []
        uploaded = 0

        for rel_path, content_bytes in files.items():
            try:
                blob_payload = {
                    "content": base64.b64encode(content_bytes).decode("ascii"),
                    "encoding": "base64",
                }
                async with session.post(
                    f"{_API}/repos/{full_repo}/git/blobs",
                    headers=hdrs,
                    json=blob_payload,
                ) as resp:
                    if resp.status not in (200, 201):
                        continue
                    blob_data = await resp.json()
                    tree_items.append({
                        "path": rel_path,
                        "mode": "100644",
                        "type": "blob",
                        "sha": blob_data["sha"],
                    })
                    uploaded += 1

                # Send keepalive every 20 files
                if uploaded % 20 == 0:
                    yield KEEPALIVE
                    yield evt({"type": "log", "message": f"⬆️ {uploaded}/{len(files)} ملف...", "level": "info"})

            except Exception as e:
                yield evt({"type": "log", "message": f"⚠️ تخطي {rel_path}: {e}", "level": "warning"})

        yield evt({"type": "log", "message": f"✅ تم رفع {uploaded} ملف", "level": "info"})
        yield KEEPALIVE

        # ── Step 6: Create tree ────────────────────────────────────────────────
        tree_payload: dict = {"tree": tree_items}
        if parent_sha:
            # Get base tree from parent commit
            async with session.get(
                f"{_API}/repos/{full_repo}/git/commits/{parent_sha}", headers=hdrs
            ) as resp:
                if resp.status == 200:
                    commit_data = await resp.json()
                    tree_payload["base_tree"] = commit_data["tree"]["sha"]

        async with session.post(
            f"{_API}/repos/{full_repo}/git/trees", headers=hdrs, json=tree_payload
        ) as resp:
            if resp.status not in (200, 201):
                body = await resp.text()
                yield evt({"type": "error", "message": f"Failed to create tree: {body[:200]}"})
                return
            tree_data = await resp.json()
            tree_sha = tree_data["sha"]

        # ── Step 7: Create commit ──────────────────────────────────────────────
        yield evt({"type": "log", "message": "💾 إنشاء الـ commit...", "level": "info"})

        commit_payload: dict = {
            "message": commit_message,
            "tree": tree_sha,
        }
        if parent_sha:
            commit_payload["parents"] = [parent_sha]

        async with session.post(
            f"{_API}/repos/{full_repo}/git/commits", headers=hdrs, json=commit_payload
        ) as resp:
            if resp.status not in (200, 201):
                body = await resp.text()
                yield evt({"type": "error", "message": f"Failed to create commit: {body[:200]}"})
                return
            commit_data = await resp.json()
            commit_sha = commit_data["sha"]

        # ── Step 8: Update branch reference ───────────────────────────────────
        ref_payload = {"sha": commit_sha, "force": True}
        ref_endpoint = f"{_API}/repos/{full_repo}/git/refs/heads/{branch}"

        async with session.patch(ref_endpoint, headers=hdrs, json=ref_payload) as resp:
            if resp.status == 422:
                # Branch doesn't exist yet — create it
                async with session.post(
                    f"{_API}/repos/{full_repo}/git/refs",
                    headers=hdrs,
                    json={"ref": f"refs/heads/{branch}", "sha": commit_sha},
                ) as create_resp:
                    if create_resp.status not in (200, 201):
                        body = await create_resp.text()
                        yield evt({"type": "error", "message": f"Failed to create branch: {body[:200]}"})
                        return
            elif resp.status not in (200, 201):
                body = await resp.text()
                yield evt({"type": "error", "message": f"Failed to update branch ref: {body[:200]}"})
                return

    # ── Done ──────────────────────────────────────────────────────────────────
    yield evt({
        "type": "done",
        "url": repo_url,
        "repo": full_repo,
        "commit": commit_sha[:7],
        "branch": branch,
        "files_uploaded": uploaded,
        "message": f"🎉 تم الرفع إلى GitHub!\n{repo_url}\n{uploaded} ملف — commit: {commit_sha[:7]}",
    })
